/*


    
    
*/
_GPL.j(function(g,d,Ia,x,h,e,y,la,ma,L,Y,u,Ja,Ka,M,na,l,oa,P,pa,v,p,qa,z,q,La,Z){function Q(){ra(r,P,Q);Ma(function(a,b){f=a;R||(R=!0,Na(),aa(),sa(r,P,aa),ta=Ka(function(){36E5<+new h-ua&&ba(!1)},5E3))})}function aa(){ua=+new h}function ba(a){R&&(R=!1,Ia(ta),Oa(),ra(r,P,aa),a||sa(r,P,Q))}function sa(a,b,c){if(l[oa])a[oa](b,c,!1);else a.attachEvent("on"+b,c)}function Na(){ca=!0;g(da).children().add("body,a").add(l).on(G,S);"20150106_t"==n&&g("iframe").each(function(a,b){try{g(b.contentWindow).on(G,
S)}catch(c){}})}function A(a){a=Y.userAgent.match(Ja(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function Pa(){if(A("Chrome")){for(var a=0;a<Y.plugins.length;a++)if("Widevine Content Decryption Module"==Y.plugins[a].name)return!1;return!0}return!1}function Qa(a){if(f!=va){a=a.target||a.srcElement;for(var b="";a;){H||(H=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){b=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}b&&(f+="&t="+e(b.substring(0,Math.max(0,
1500-f.length))));f+="&rt="+(+new h-wa);H&&(f+="&data_tag="+e(H));"/"!=y.pathname&&(f+="&mk="+e(d.B64.encode(ea().substring(0,Math.max(0,1500-f.length)))))}d.log("Popping to: "+f);a="ld893_"+(N?"_"+e(N)+"_":"")+"_"+B();if(b=l.open("","_blank"))b.name=a,b.location.href=f;return b}function ea(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var b=[];g("title").length&&(b=b.concat(a(g("title").text())));g('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var c=
g.trim(g(this).attr("content"));c&&c.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(c)))});return g.trim(function(a){var b=[];g.each(a,function(a,c){-1==g.inArray(c,b)&&b.push(c)});return b}(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function xa(){var a=y.href.substr(0,1500),b="/"!=y.pathname?ea():"",a=a.replace(/:/g,"%3A"),b=b.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),c=d.getSubId?"&subid="+d.getSubId("z7b85"):"",a=e(d.B64.encode(a+"::z-"+C+"-"+ya+"::"+b)),b="&cb="+fa,b=b+
("&data_fr="+(za(s)?"false":"true"));return d.proto+Aa+"/pops?c="+a+"&a=1&ch="+e(O)+c+b}function ra(a,b,c){if(l[pa])a[pa](b,c,!1);else a.detachEvent("on"+b,c)}function Oa(){ca=!1;g(da).children().add("body,a").add(l).off(G,S);"20150106_t"==n&&g("iframe").each(function(a,b){try{g(b.contentWindow).off(G,S)}catch(c){}})}function Ra(a){a=a||l.event||{};if(Sa&&r.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}function I(a,
b){a=u(a,10);isNaN(a)&&(a=u(T&&T.getItem(b)||d.gc(b,10),10)||0);return a}function za(a){return(new h(1E3*(a||0))).toDateString()==(new h).toDateString()}function U(){s|=0;k|=0;E|=0;var a=B(),b=k&&!za(s);b&&(k=0,m.set(q,k));var c=!F||a-s>=J&&k<F,a=a-E>=w;return!t&&b||c&&a}function S(a){if(!Ra(a)){var b=ca&&Ta(),c=b&&Qa(a);if(b&&"mousedown"==a.type&&Ba)try{a.target.click()}catch(Xa){}c&&!c.closed?(ba(!0),Ua(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popsuccess&u="+e(f)+"&cid="+d.vars.cid+
"&pid="+C+"&r="+999999999*Math.random(),V&&x(V),W&&x(W)):c&&c.closed?W||(W=M(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+e(f)+"&location="+e(y.hostname)+"&pid="+C+"&tag="+e(H||"")+"&r="+999999999*Math.random()},1E3)):b&&(V||(V=M(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+e(f)+"&location="+e(y.hostname)+"&pid="+C+"&tag="+e(H||"")+"&r="+999999999*Math.random()},1E3)))}}function Ta(){if(!m.swf)return!0;s=I(m.get(v),v);316808>Ca.score&&(k=
I(m.get(q),q));var a=Da(m.get(p));E=I(a[K],p);return U()}function B(){return la(new h/1E3)}function Ea(a,b,c){m.set(a,c);c=B();T&&T.setItem(a,c);b=u(b,10);var d=new h;d.setSeconds(d.getSeconds()+b);r.cookie=a+"="+c+";expires="+d.toUTCString()+";path=/;domain="+K}function Ua(){var a=B();Ea(v,J,a);m.set(La,a);s=a;m.set(q,++k);w&&Ea(p,w,X+(X&&",")+K+":"+a)}function Da(a){var b={},c=B(),d=[];a=(a||"").split(",");if(a.length){for(var e=0;e<a.length;++e){var f=a[e].split(":"),g=u(f[1],10);c-g<w&&(b[f[0]]=
g,d.push(f[0]+":"+g))}X=d.join(",");m.set(p,X)}return b}function ga(){return U()||t?1:B()-(u(E,10)||0)<w?Infinity:k>=F?"US"==d.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(d.vars.cid)?88620:59858:"US"==d.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(d.vars.cid)?59858:49928}function Va(a){"US"==d.vars.cid?ha(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(d.vars.cid)?ha(a,59858,88620):ha(a,49928,59858);return U()}function ha(a,b,c){a>=b&&(J=0,a>=c&&k>=F&&(k=ma(0,F-1)))}function Fa(){x(ia);
if(!t&&1735!=C){var a=ga(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+ya+"&action=r&q=",c="/"!=y.pathname?ea():"",b=b+e(c.substring(0,Math.max(0,1500-b.length)));l[fa]({url:b,score:a});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&u="+e(y.hostname)+"&r="+999999999*Math.random()}}function Ma(a){!function c(){d.gc(qa)||m.get(["frt","_GPL_oo_z7b85",v,p,q,Z],function(e){if(e.v.frt){if("1750"==C){var f=u(e.v._GPL_oo_z7b85,10)||0;if(86400>la(new h/1E3)-f)return}n||(f="20150106_c 20150106_c 20150106_c 20150106_c 20150106_c 20150106_c 20150106_c 20150106_c 20150106_c 20150106_t".split(" "),
n=e.v[Z],n&&-1!=f.indexOf(n)||(n=f[Math.floor(Math.random()*f.length)],m.set(Z,n)));l[fa]=function(c){Wa(c,a)};f=B();s=I(e.v[v],v);k=I(e.v[q],q);e=Da(e.v[p]);E=I(e[K],p);if(U()){e=ga();ja=+new h;var g=r.createElement("script");g.src=xa()+"&ms="+e+"&r="+f;g.onerror=Fa;da.appendChild(g);ia=M(Fa,15E3)}else e=ga(),d.log("minScoreNeeded: "+e),Infinity>e&&!Ga&&!t&&(ja=+new h,d.insertJS(xa()+"&ms="+e+"&r="+f),Ga=!0),x(ka),ka=M(c,1E3*(5+ma(f,s+J,E+w)-f))}})}()}function Wa(a,b){x(ia);var c=+new h-ja;N="";
a&&(a.cid&&(N=a.cid,a.url||(a.url=d.proto+Aa+"/click?c="+e(N),a.url+=d.getSubId?"&subid="+d.getSubId("z7b85"):"",a.url+=n?"&data_test="+e(n):"",a.url+="&data_fb="+(Pa()?"yes":"no"),a.url+="&data_rtt="+c,a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0))),t&&!a.cid&&(a.url=va,a.cid="xr"),c=u(a.score,10),t||0<c&&Va(c))&&(wa=+new h,x(ka),a.url&&a.expires&&(x(Ha),Ha=M(function(){ba(!0);Q()},1E3*u(a.expires,10))),Ca={score:c,now:new h/1},b(a.url,c))}var m=d.items.e6a00,r=l.document,
da=r.body,T=l.localStorage,Ba=A("chrome");L=A("firefox");A("opera");na=A("safari");A("webkit");var O=d.item_vars["22555_ch"]||d.item_vars.ch||"",J,s,E;z=(z=d.dt())&&z.inherited&&z.inherited.t||[];var t="x"==O||-1<z.indexOf("adult")||0==z.length&&0<g('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;t&&(-1==z.indexOf("adult_block")?O="x":(O="x-issue",t=!1));var w,Aa="s.ptrk-wn.com",R=!1,ta,ua,ca=!1,K=d.gd(),f,wa=0,ja=0,Ha,X="",k=0,F,Ca={},N="",ka,Ga=!1,n,V,W,ia,H,G="click";if(Ba||na)G="mousedown";
else if(L||r.all||A("trident"))G="mouseup";L=d.zoneid("z7b85",!0).split("_");var ya=L[0],C=L[1]||d.vars.pid,va="http://secure.xsrving.com/display?size=800x600&ch="+e(O)+"&referer="+e(K),Sa=!1,fa=d.rs(20);d.canLoad("ld893")||d.gc(qa)||(l.name||"").match(/^a652c_/)||1797==C&&"GB"==d.vars.cid||"facebook.com"==K||(t?(F=J=0,w=180,v+="_xr",p+="_xr",q+="_xr"):(J=360,F=4,w=360),Q())},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,
setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","z7b85_bl1","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
